# Generated by Django 5.1 on 2024-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShowcase', '0002_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='current_location',
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
