# Generated by Django 5.1 on 2024-08-22 18:19

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=15)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('last_login', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('location_id', models.IntegerField(blank=True, default='', null=True)),
                ('user_birthdate', models.DateField(default=datetime.date.today)),
                ('bio', models.CharField(blank=True, default='', max_length=250)),
                ('linkedin', models.CharField(blank=True, default='', max_length=20)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('company', models.CharField(default='N/A', max_length=50)),
                ('job_title', models.CharField(default='N/A', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
