# Generated by Django 5.1 on 2024-09-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShowcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
